### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by khantkyawkhaung** [staytu/staytu.github.io#2]
Links to some minor pages like terms, help. Should contain links to social media accounts (SVG icons are already uploaded to the repository).

**Comment by ydcjeff** [comment]
@khantkyawkhaung I have used static site generators and here is the link https://staytu.surge.sh

how do you think?
It is the default design of [VuePress](https://vuepress.vuejs.org) and I haven't changed anything.
Since it is a static site generators, all the contents can be written in markdown.

**Comment by khantkyawkhaung** [comment]
It's really nice. But we still need **CSS** files for fully customized web design? Anyway we should use a markdown to **HTML** converter like that.

**Comment by ydcjeff** [comment]
@khantkyawkhaung do you want a single web design for a single page?
Or a general customized design for the whole site?

**Comment by khantkyawkhaung** [comment]
General customized design. But the home page looks pretty different.

**Comment by ydcjeff** [comment]
@khantkyawkhaung so for using customized design every time on the pages except home page, there is static site generator called [jekyll](https://jekyllrb.com). You can set up template designs for every common pages, also home page.
Also, that enables us to write content in markdown.
