### ISSUE TITLE
Tutorials page

### ISSUE THREAD

**Issue by khantkyawkhaung** [staytu/staytu.github.io#3]
This is the design by Zay Yar Tun
![74408284_2455437228108612_7072161250595045376_n](https://user-images.githubusercontent.com/30836062/69902341-be8d5680-13ba-11ea-8a55-e1ded211d63a.jpg)

In dynamic web pages, article previews are loaded from databases. In our system, I would like to use **JSON**s as databases readable by everyone. In addition, a search box for searching article should be included.

**Comment by Jamie1606** [comment]
I will make the new tutorials into one group for this week and the older ones will appear below it. Is it okay?
